const { Client } = require('pg');

const tryConnect = async () => {
  const password = encodeURIComponent('7w.p2%$JC#Fc.%E');
  const connStr = `postgresql://postgres.mdgcorkmkovemafxefbn:${password}@aws-0-eu-central-1.pooler.supabase.com:6543/postgres`;
  const client = new Client({ connectionString: connStr });
  try {
    await client.connect();
    console.log(`SUCCESS connected!`);
    
    await client.query(`
      create table if not exists users (
        id bigint generated by default as identity primary key,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null,
        name text,
        phone text,
        email text,
        tool_name text,
        input_data jsonb,
        output_result text
      );
      ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
    `);
    console.log('Table users created and RLS disabled!');
    
    await client.end();
  } catch (e) {
    console.log(`Failed: ${e.message}`);
  }
};

tryConnect();
