const { Client } = require('pg');

const tryConnect = async () => {
  const password = encodeURIComponent('7w.p2%$JC#Fc.%E');
  // From screenshot: eu-central-1
  const connStr = `postgresql://postgres.mdgcorkmkovemafxefbn:${password}@aws-0-eu-central-1.pooler.supabase.com:6543/postgres`;
  console.log(`Trying eu-central-1...`);
  const client = new Client({ connectionString: connStr });
  try {
    await client.connect();
    console.log(`SUCCESS connected!`);
    
    const res = await client.query(`
      create table if not exists leads (
        id bigint generated by default as identity primary key,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null,
        name text,
        phone text,
        email text,
        tool_name text,
        input_data jsonb,
        output_result text
      );
    `);
    console.log('Table created!', res);
    await client.end();
    return;
  } catch (e) {
    console.log(`Failed: ${e.message}`);
  }
};

tryConnect();
